services:
  - type: web
    name: fovdark-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build:prod
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fovdark-db
          property: connectionString
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80

databases:
  - name: fovdark-db
    databaseName: fovdark
    user: fovdark_user
    plan: starter