services:
  - type: web
    name: rest-express
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production